mdapi_output/objects/Auth_Event__e.object
<CustomObject>
    <label>Auth Event</label>
    <pluralLabel>Auth Events</pluralLabel>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output/objects/Dataset_Event__e.object
<CustomObject>
    <label>Dataset Event</label>
    <pluralLabel>Dataset Events</pluralLabel>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dataset_Id__c</fullName>
        <label>Dataset Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EventHelper.cls
public with sharing class EventHelper 
{
	public static void PublishAuthEvent(string provider, string action)
    {
        Auth_Event__e authData = new Auth_Event__e
            (
                Provider__c = provider,
                Action__c = action
            );
        
        EventBus.publish(authData);
    }
    
    public static void PublishDatasetEvent(string dataSetId, string action)
    {
        Dataset_Event__e dataSetData = new Dataset_Event__e
            (
                Dataset_Id__c = dataSetId,
                Action__c = action
            );
        
        EventBus.publish(dataSetData);
    }
    
    public static void HandleAuthTrigger(List<Auth_Event__e> items)
    {
        for(Auth_Event__e item : items)
        {
        }
    }
}