mdapi_output/objects/Dataset__c.object
<CustomObject>
    <label>Dataset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datasets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Model_Id__c</fullName>
        <label>Model Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output/objects/Image_Classification__c.object
<CustomObject>
    <label>Image Classification</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Classifier__c</fullName>
        <label>Classifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
</CustomObject>

mdapi_output/objects/Image_Classification_Result__c.object
<CustomObject>
    <label>Image Classification Result</label>
    <nameField>
        <displayFormat>ICR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Classification Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Image_Classification__c</fullName>
        <label>Image Classification</label>
        <referenceTo>Image_Classification__c</referenceTo>
        <relationshipLabel>Image Classification Results</relationshipLabel>
        <relationshipName>Image_Classification_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi_output/classes/Upload_ImageController.cls
public with sharing class Upload_ImageController 
{
    @AuraEnabled
    public static Id PushToCustomObject(String fileName, String documentId, string model)
    {
        ContentDistribution cd = new ContentDistribution();
        cd.Name = fileName;
        cd.ContentVersionId = [SELECT Id FROM ContentVersion WHERE ContentDocumentId=:documentId].Id;
        insert cd;

        Image_Classification__c  ic = new Image_Classification__c
            (
		        Status__c = 'Uploaded',
	    	    Url__c	= [SELECT ContentDownloadUrl FROM ContentDistribution WHERE ContentVersionId=:cd.ContentVersionId].ContentDownloadUrl,
                Classifier__c = model
            );
        insert ic;

        EventHelper.PublishClassificationEvent(ic.Id, Constants.Classification_Created);
        
        return ic.Id;
    }
    
    @AuraEnabled
    public static List<Image_Classification_Result__c> GetResults(Id classificationId)
    {
        return [SELECT Label__c, Result__c FROM Image_Classification_Result__c WHERE Image_Classification__c =: classificationId];
    }
    
    @AuraEnabled
    public static List<Dataset__c> GetModels()
    {
        return [SELECT Id, Name, Model_Id__c FROM Dataset__c WHERE Id != NULL];
    }

    @AuraEnabled
    public static string CreateRecordId(String recordId)
    {
        List<Account> accs=[Select Id,Name from Account where Name = 'Tmp'];
    
        if (accs.size() <= 0)
        {
            Account  acc = new Account();
            // create temporary Record
            acc.Name = 'Tmp';
            Insert acc;
            return acc.Id;
        }
        return accs[0].Id;
    }
    
    @AuraEnabled
    public static String getSessionId() 
    {
        return UserInfo.getSessionId();
    }
}