mdapi_output/objects/Image_Classification__c.object
<CustomObject>
    <label>Image Classification</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Classifier__c</fullName>
        <label>Classifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
</CustomObject>

mdapi_output/objects/Image_Classification_Result__c.object
<CustomObject>
    <label>Image Classification Result</label>
    <nameField>
        <displayFormat>ICR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Classification Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Image_Classification__c</fullName>
        <label>Image Classification</label>
        <referenceTo>Image_Classification__c</referenceTo>
        <relationshipLabel>Image Classification Results</relationshipLabel>
        <relationshipName>Image_Classification_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/VisionPredictHelper.cls
public with sharing class VisionPredictHelper 
{
	@InvocableMethod(label='Submit Image for Classification to Einstein Vision')
    public static void SubmitImage(List<Id> itemIds)
    {
        EinsteinVision_PredictionService ps = new EinsteinVision_PredictionService();
        
        Map<Image_Classification__c, EinsteinVision_PredictionResult> classificationResults = new Map<Image_Classification__c, EinsteinVision_PredictionResult>();
        
        List<Image_Classification__c> items = [SELECT Url__c, Status__c, Classifier__c FROM Image_Classification__c WHERE Id IN: itemIds];
        
        for(Image_Classification__c item : items)
        {
            EinsteinVision_PredictionResult results = ps.predictUrl(item.Classifier__c, item.Url__c, null);
             
            classificationResults.put(item, results);
        }
        
        List<Image_Classification_Result__c> results = new List<Image_Classification_Result__c>();
        
        for(Image_Classification__c item : classificationResults.keySet())
        {
            for(EinsteinVision_Probability result : classificationResults.get(item).probabilities)
            {
                Image_Classification_Result__c res = new Image_Classification_Result__c
                    (
                        Image_Classification__c = item.Id,
                        Label__c = result.label,
                        Result__c = result.probability
                    );
                
                results.add(res);
            }
            
            item.Status__c = 'Completed';
            EventHelper.PublishClassificationEvent(item.Id, Constants.Classification_Results);
        }
        
        if(!results.isEmpty())
        {
            upsert items;
            insert results;
		}
    }
}