mdapi_output/objects/Image_Classification__c.object
<CustomObject>
    <label>Image Classification</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Upload_ImageController.cls
public with sharing class Upload_ImageController {
    @AuraEnabled
    public static string PushToCustomObject(String fileName, String documentId)
    {
        ContentDistribution cd = new ContentDistribution();
        cd.Name = fileName;
        cd.ContentVersionId = [SELECT Id FROM ContentVersion WHERE ContentDocumentId=:documentId].Id;
        insert cd;

        Image_Classification__c  ic = new Image_Classification__c();
        // what is the status expected?
        ic.Status__c = filename+' Uploaded';
        // need to retrieve public link sharing here
        ic.Url__c	= [SELECT ContentDownloadUrl FROM ContentDistribution WHERE ContentVersionId=:cd.ContentVersionId].ContentDownloadUrl;
        Insert Ic;

        return null;
    }

     @AuraEnabled
    public static string CreateRecordId(String recordId)
    {
        List<Account> accs=[Select Id,Name from Account where Name = 'Tmp'];
    
        if (accs.size() <= 0)
        {
            Account  acc = new Account();
            // create temporary Record
            acc.Name = 'Tmp';
            Insert acc;
            return acc.Id;
        }
        return accs[0].Id;
    }
}